version: "3.3"
services:
    nginx-proxy:
        restart: unless-stopped
        build:
            context: ./web
            dockerfile: dockerfile
        ports:
            - "80:80"
            - "443:443"
        networks:
            - main-internal-network
networks:
    # Cross Application Networks
    main-internal-network:
        driver: bridge